branch-defaults:
  master:
    environment: blog1-env-2
    group_suffix: null
global:
  application_name: blog1
  branch: null
  default_ec2_keyname: null
  default_platform: Puma with Ruby 2.6 running on 64bit Amazon Linux/2.12.2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
