default:
  host: <%= ENV['REDIS_HOST'] || "localhost" %>
  port: 6379
  db: 0
development:
  host: <%= ENV['REDIS_HOST'] || "localhost" %>
  port: 6379
  db: 1
production:
  host: 127.0.0.1
  port: 6379
  db: 5
